"""Markdown and JSON output rendering for agency dossiers."""

from __future__ import annotations

import re
from pathlib import Path

from blackbox import __version__
from blackbox.models import AgencyDossier, SectionStatus


def _slugify(name: str) -> str:
    slug = name.lower().strip()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    return slug.strip("-")


def render_markdown(dossier: AgencyDossier) -> str:
    """Render a complete markdown dossier report."""
    ctx = dossier.rfp_context
    lines = [
        f"# Agency Dossier: {dossier.agency_name}",
        "",
        f"**Generated:** {dossier.generated_at.strftime('%Y-%m-%d %H:%M UTC')}  ",
        f"**Solicitation:** {ctx.solicitation_number or 'N/A'}  ",
        f"**Scope:** {ctx.scope or 'Not specified'}  ",
        f"**Contract Type:** {ctx.contract_type.value}  ",
        f"**Estimated Value:** {ctx.estimated_value or 'Unknown'}  ",
        "",
        "---",
        "",
    ]

    # Qualification Score section
    if dossier.score:
        s = dossier.score
        lines.append("## Qualification Score")
        lines.append("")
        lines.append(f"**Overall: {s.overall_score}/100 — {s.recommendation.value}**")
        lines.append("")
        lines.append("| Dimension | Score | Weight | Rationale |")
        lines.append("|-----------|-------|--------|-----------|")
        for d in s.dimensions:
            lines.append(f"| {d.name} | {d.score} | {d.weight:.0%} | {d.rationale} |")
        lines.append("")

        if s.strengths:
            lines.append("**Strengths:**")
            for st in s.strengths:
                lines.append(f"- {st}")
            lines.append("")

        if s.risks:
            lines.append("**Risks:**")
            for r in s.risks:
                lines.append(f"- {r}")
            lines.append("")

        if s.go_no_go_summary:
            lines.append(f"**Go/No-Go:** {s.go_no_go_summary}")
            lines.append("")

        lines.append("---")
        lines.append("")
    else:
        lines.append("## Qualification Score")
        lines.append("")
        lines.append("**Scoring unavailable** — qualification scoring failed. Review the research findings manually.")
        lines.append("")
        lines.append("---")
        lines.append("")

    # Research Findings
    lines.append("## Research Findings")
    lines.append("")

    for i, section in enumerate(dossier.sections, 1):
        lines.append(f"### {i}. {section.title}")

        if section.status == SectionStatus.INSUFFICIENT_DATA:
            lines.append("**INSUFFICIENT DATA**")
            lines.append("")
            lines.append(section.summary)
        else:
            lines.append(f"*Confidence: {section.confidence:.0%}*")
            lines.append("")
            lines.append(section.summary)

            if section.key_findings:
                lines.append("")
                lines.append("**Key Findings:**")
                for f in section.key_findings:
                    lines.append(f"- {f}")

            if section.sources:
                lines.append("")
                lines.append("**Sources:**")
                for src in section.sources:
                    date_suffix = f" ({src.published_date})" if src.published_date else ""
                    title = src.title or src.url
                    lines.append(f"- [{title}]({src.url}){date_suffix}")

        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append(
        f"*Report generated by Blackbox v{__version__} | "
        f"{dossier.total_queries} queries | "
        f"{dossier.total_sources} sources | "
        f"Est. cost: ${dossier.llm_cost_estimate_usd:.2f}*"
    )

    return "\n".join(lines)


def render_json(dossier: AgencyDossier) -> str:
    """Serialize dossier to formatted JSON."""
    return dossier.model_dump_json(indent=2)


def write_output(
    dossier: AgencyDossier, output_dir: Path, fmt: str = "both"
) -> list[Path]:
    """Write dossier to files. Returns list of paths written."""
    output_dir.mkdir(parents=True, exist_ok=True)
    slug = _slugify(dossier.agency_name)
    written: list[Path] = []

    if fmt in ("md", "both"):
        md_path = output_dir / f"{slug}-dossier.md"
        md_path.write_text(render_markdown(dossier))
        written.append(md_path)

    if fmt in ("json", "both"):
        json_path = output_dir / f"{slug}-dossier.json"
        json_path.write_text(render_json(dossier))
        written.append(json_path)

    return written
