import type { PaperclipPluginManifestV1 } from "@paperclipai/plugin-sdk";
import {
  DEFAULT_CONFIG,
  EXPORT_NAMES,
  JOB_KEYS,
  PAGE_ROUTE,
  PLUGIN_ID,
  PLUGIN_VERSION,
  SLOT_IDS,
  TOOL_NAMES,
  WEBHOOK_KEYS,
} from "./constants.js";

const manifest: PaperclipPluginManifestV1 = {
  id: PLUGIN_ID,
  apiVersion: 1,
  version: PLUGIN_VERSION,
  displayName: "Central de Operações",
  description: "Central operacional interna para diagnósticos, intake de issues, notas de workspace, ferramentas, streams, jobs e follow-up por webhook.",
  author: "Paperclip",
  categories: ["ui", "automation", "workspace", "connector"],
  capabilities: [
    "companies.read",
    "projects.read",
    "project.workspaces.read",
    "issues.read",
    "issues.create",
    "issues.update",
    "issue.comments.read",
    "issue.comments.create",
    "agents.read",
    "agents.pause",
    "agents.resume",
    "agents.invoke",
    "agent.sessions.create",
    "agent.sessions.list",
    "agent.sessions.send",
    "agent.sessions.close",
    "goals.read",
    "goals.create",
    "goals.update",
    "activity.log.write",
    "metrics.write",
    "telemetry.track",
    "plugin.state.read",
    "plugin.state.write",
    "events.subscribe",
    "events.emit",
    "jobs.schedule",
    "webhooks.receive",
    "http.outbound",
    "secrets.read-ref",
    "agent.tools.register",
    "instance.settings.register",
    "ui.sidebar.register",
    "ui.page.register",
    "ui.detailTab.register",
    "ui.dashboardWidget.register",
    "ui.commentAnnotation.register",
    "ui.action.register",
  ],
  entrypoints: {
    worker: "./dist/worker.js",
    ui: "./dist/ui",
  },
  instanceConfigSchema: {
    type: "object",
    properties: {
      showSidebarEntry: {
        type: "boolean",
        title: "Exibir entrada na barra lateral",
        default: DEFAULT_CONFIG.showSidebarEntry,
      },
      showSidebarPanel: {
        type: "boolean",
        title: "Exibir painel lateral",
        default: DEFAULT_CONFIG.showSidebarPanel,
      },
      showProjectSidebarItem: {
        type: "boolean",
        title: "Exibir atalho lateral do projeto",
        default: DEFAULT_CONFIG.showProjectSidebarItem,
      },
      showCommentAnnotation: {
        type: "boolean",
        title: "Exibir anotação em comentário",
        default: DEFAULT_CONFIG.showCommentAnnotation,
      },
      showCommentContextMenuItem: {
        type: "boolean",
        title: "Exibir ação de comentário",
        default: DEFAULT_CONFIG.showCommentContextMenuItem,
      },
      enableWorkspaceDemos: {
        type: "boolean",
        title: "Habilitar acesso ao workspace",
        default: DEFAULT_CONFIG.enableWorkspaceDemos,
      },
      enableProcessDemos: {
        type: "boolean",
        title: "Habilitar diagnósticos locais",
        default: DEFAULT_CONFIG.enableProcessDemos,
        description: "Permite diagnósticos locais controlados com subprocessos nos workspaces do projeto.",
      },
      secretRefExample: {
        type: "string",
        title: "Referência de segredo",
        default: DEFAULT_CONFIG.secretRefExample,
      },
      httpDemoUrl: {
        type: "string",
        title: "URL do endpoint HTTP",
        default: DEFAULT_CONFIG.httpDemoUrl,
      },
      allowedCommands: {
        type: "array",
        title: "Comandos de processo permitidos",
        items: {
          type: "string",
          enum: DEFAULT_CONFIG.allowedCommands,
        },
        default: DEFAULT_CONFIG.allowedCommands,
      },
      workspaceScratchFile: {
        type: "string",
        title: "Arquivo de notas do workspace",
        default: DEFAULT_CONFIG.workspaceScratchFile,
      },
    },
  },
  jobs: [
    {
      jobKey: JOB_KEYS.heartbeat,
      displayName: "Heartbeat Operacional",
      description: "Job periódico que registra a saúde do runtime do plugin e a atividade recente.",
      schedule: "*/15 * * * *",
    },
  ],
  webhooks: [
    {
      endpointKey: WEBHOOK_KEYS.demo,
      displayName: "Entrada de Incidente",
      description: "Aceita payloads de webhook e pode criar uma issue de follow-up quando empresa e título são informados.",
    },
  ],
  tools: [
    {
      name: TOOL_NAMES.echo,
      displayName: "Eco de Nota Operacional",
      description: "Retorna a mensagem enviada e o contexto atual da execução para validação rápida.",
      parametersSchema: {
        type: "object",
        properties: {
          message: { type: "string" },
        },
        required: ["message"],
      },
    },
    {
      name: TOOL_NAMES.companySummary,
      displayName: "Resumo Operacional da Empresa",
      description: "Resume a empresa atual usando as APIs de domínio do Paperclip.",
      parametersSchema: {
        type: "object",
        properties: {},
      },
    },
    {
      name: TOOL_NAMES.createIssue,
      displayName: "Criar Issue Operacional",
      description: "Cria uma issue no projeto atual a partir de uma chamada de ferramenta do agente.",
      parametersSchema: {
        type: "object",
        properties: {
          title: { type: "string" },
          description: { type: "string" },
        },
        required: ["title"],
      },
    },
  ],
  ui: {
    slots: [
      {
        type: "page",
        id: SLOT_IDS.page,
        displayName: "Central de Operações",
        exportName: EXPORT_NAMES.page,
        routePath: PAGE_ROUTE,
      },
      {
        type: "settingsPage",
        id: SLOT_IDS.settingsPage,
        displayName: "Configurações da Central de Operações",
        exportName: EXPORT_NAMES.settingsPage,
      },
      {
        type: "dashboardWidget",
        id: SLOT_IDS.dashboardWidget,
        displayName: "Central de Operações",
        exportName: EXPORT_NAMES.dashboardWidget,
      },
      {
        type: "sidebar",
        id: SLOT_IDS.sidebar,
        displayName: "Central de Operações",
        exportName: EXPORT_NAMES.sidebar,
      },
      {
        type: "sidebarPanel",
        id: SLOT_IDS.sidebarPanel,
        displayName: "Painel Operacional",
        exportName: EXPORT_NAMES.sidebarPanel,
      },
      {
        type: "projectSidebarItem",
        id: SLOT_IDS.projectSidebarItem,
        displayName: "Operações",
        exportName: EXPORT_NAMES.projectSidebarItem,
        entityTypes: ["project"],
      },
      {
        type: "detailTab",
        id: SLOT_IDS.projectTab,
        displayName: "Operações",
        exportName: EXPORT_NAMES.projectTab,
        entityTypes: ["project"],
      },
      {
        type: "detailTab",
        id: SLOT_IDS.issueTab,
        displayName: "Operações",
        exportName: EXPORT_NAMES.issueTab,
        entityTypes: ["issue"],
      },
      {
        type: "taskDetailView",
        id: SLOT_IDS.taskDetailView,
        displayName: "Visão Operacional da Task",
        exportName: EXPORT_NAMES.taskDetailView,
        entityTypes: ["issue"],
      },
      {
        type: "toolbarButton",
        id: SLOT_IDS.toolbarButton,
        displayName: "Ação Operacional",
        exportName: EXPORT_NAMES.toolbarButton,
        entityTypes: ["project", "issue"],
      },
      {
        type: "contextMenuItem",
        id: SLOT_IDS.contextMenuItem,
        displayName: "Contexto Operacional",
        exportName: EXPORT_NAMES.contextMenuItem,
        entityTypes: ["project", "issue"],
      },
      {
        type: "commentAnnotation",
        id: SLOT_IDS.commentAnnotation,
        displayName: "Anotação Operacional do Comentário",
        exportName: EXPORT_NAMES.commentAnnotation,
        entityTypes: ["comment"],
      },
      {
        type: "commentContextMenuItem",
        id: SLOT_IDS.commentContextMenuItem,
        displayName: "Ação Operacional do Comentário",
        exportName: EXPORT_NAMES.commentContextMenuItem,
        entityTypes: ["comment"],
      },
    ],
    launchers: [
      {
        id: "central-operacoes-launcher",
        displayName: "Modal da Central de Operações",
        placementZone: "toolbarButton",
        entityTypes: ["project", "issue"],
        action: {
          type: "openModal",
          target: EXPORT_NAMES.launcherModal,
        },
        render: {
          environment: "hostOverlay",
          bounds: "wide",
        },
      },
    ],
  },
};

export default manifest;
