import { api } from "./client";

export interface Deliverable {
  id: string;
  companyId: string;
  slug: string;
  title: string;
  documentType: string | null;
  deliverableStatus: string | null;
  agentId: string | null;
  createdByAgentId: string | null;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
  agentName: string | null;
  agentRole: string | null;
}

export const deliverablesApi = {
  list: (companyId: string, status?: string) => {
    const params = status ? `?status=${encodeURIComponent(status)}` : "";
    return api.get<Deliverable[]>(`/companies/${companyId}/deliverables${params}`);
  },

  updateStatus: (companyId: string, id: string, deliverableStatus: string) =>
    api.patch<Deliverable>(`/companies/${companyId}/deliverables/${id}`, { deliverableStatus }),
};
