#!/bin/bash
set -euo pipefail

# CLAUDE_CODE_OAUTH_TOKEN is the env var the Claude CLI reads on every invocation
# for subscription-based auth (set via the ECS secrets block in ecs.tf).
# The value is a setup token generated by `claude setup-token` on a locally
# authenticated machine. No explicit login step is needed — the CLI uses it
# directly as a Bearer token.

# Inject Codex/OpenAI subscription credentials
if [[ -n "${CODEX_CREDENTIALS:-}" ]]; then
  mkdir -p /paperclip/.codex
  echo "$CODEX_CREDENTIALS" > /paperclip/.codex/credentials.json
  echo "[entrypoint] Codex credentials written to /paperclip/.codex/credentials.json"
fi


# Bootstrap the first admin invite if requested
# Set BOOTSTRAP_CEO_BASE_URL to your public URL (e.g. https://app.example.com)
# The invite URL will be printed to container logs (e.g. CloudWatch).
# Safe to leave set permanently — skips automatically once an admin exists.
if [[ -n "${BOOTSTRAP_CEO_BASE_URL:-}" ]]; then
  echo "[entrypoint] Running bootstrap-ceo (base-url=${BOOTSTRAP_CEO_BASE_URL})"
  node --import ./cli/node_modules/tsx/dist/loader.mjs cli/src/index.ts auth bootstrap-ceo \
    --base-url "${BOOTSTRAP_CEO_BASE_URL}" || true
fi


exec node --import ./server/node_modules/tsx/dist/loader.mjs server/dist/index.js
