#!/usr/bin/env bash
set -euo pipefail

# End-to-end smoke test for agent-facing API availability.
# Required env vars:
# - PAPERCLIP_URL
# - PAPERCLIP_COMPANY_ID
# - PAPERCLIP_AGENT_ID
# - PAPERCLIP_AGENT_API_KEY
#
# Optional:
# - PAPERCLIP_SMOKE_ISSUE_ID (explicit issue id to use for write checks)
# - PAPERCLIP_SMOKE_CREATE_EPHEMERAL_ISSUE=true|false (default: true)

: "${PAPERCLIP_URL:?Missing PAPERCLIP_URL (e.g. http://127.0.0.1:3100)}"
: "${PAPERCLIP_COMPANY_ID:?Missing PAPERCLIP_COMPANY_ID}"
: "${PAPERCLIP_AGENT_ID:?Missing PAPERCLIP_AGENT_ID}"
: "${PAPERCLIP_AGENT_API_KEY:?Missing PAPERCLIP_AGENT_API_KEY}"

if ! command -v jq >/dev/null 2>&1; then
  echo "FAIL: missing dependency 'jq' (install jq and re-run scripts/smoke/agent-api.sh)" >&2
  exit 1
fi

BASE_URL="${PAPERCLIP_URL%/}"
AUTH_HEADER="Authorization: Bearer ${PAPERCLIP_AGENT_API_KEY}"
CURL_OPTS=(
  "--connect-timeout" "${PAPERCLIP_CURL_CONNECT_TIMEOUT_SEC:-5}"
  "--max-time" "${PAPERCLIP_CURL_MAX_TIME_SEC:-30}"
)
CREATED_EPHEMERAL_ISSUE_ID=""
RUN_ID=""

run_curl() {
  local context="$1"
  shift
  if ! curl "${CURL_OPTS[@]}" "$@"; then
    echo "FAIL: curl failed (${context})" >&2
    exit 1
  fi
}

cleanup_ephemeral_issue() {
  if [[ -z "${CREATED_EPHEMERAL_ISSUE_ID}" || -z "${RUN_ID}" ]]; then
    return 0
  fi
  CLEANUP_BODY='{"status":"cancelled","comment":"smoke cleanup: auto-cancel ephemeral issue"}'
  curl "${CURL_OPTS[@]}" -sf -X PATCH \
    -H "${AUTH_HEADER}" \
    -H "Content-Type: application/json" \
    -H "X-Paperclip-Run-Id: ${RUN_ID}" \
    "${BASE_URL}/api/issues/${CREATED_EPHEMERAL_ISSUE_ID}" \
    -d "${CLEANUP_BODY}" >/dev/null || true
}
trap cleanup_ephemeral_issue EXIT

echo "==> 1/6 Health endpoint"
run_curl "GET /api/health" -sf "${BASE_URL}/api/health" >/dev/null
echo "OK: /api/health"

echo "==> 2/6 Agent identity"
ME_JSON="$(run_curl "GET /api/agents/me" -sf -H "${AUTH_HEADER}" "${BASE_URL}/api/agents/me")"
ME_AGENT_ID="$(printf "%s" "${ME_JSON}" | jq -r '.id')"
if [[ "${ME_AGENT_ID}" != "${PAPERCLIP_AGENT_ID}" ]]; then
  echo "FAIL: /api/agents/me returned id ${ME_AGENT_ID}, expected ${PAPERCLIP_AGENT_ID}" >&2
  exit 1
fi
echo "OK: /api/agents/me"

echo "==> 3/6 Inbox-lite"
INBOX_JSON="$(run_curl "GET /api/agents/me/inbox-lite" -sf -H "${AUTH_HEADER}" "${BASE_URL}/api/agents/me/inbox-lite")"
echo "OK: /api/agents/me/inbox-lite"

echo "==> 4/6 Resolve latest run id"
RUNS_JSON="$(
  run_curl "GET /api/companies/:companyId/heartbeat-runs (agentId filter)" \
    -sf -G \
    -H "${AUTH_HEADER}" \
    --data-urlencode "agentId=${PAPERCLIP_AGENT_ID}" \
    --data-urlencode "limit=1" \
    "${BASE_URL}/api/companies/${PAPERCLIP_COMPANY_ID}/heartbeat-runs"
)"
RUN_ID="$(printf "%s" "${RUNS_JSON}" | jq -r '.[0].id // empty')"
if [[ -z "${RUN_ID}" ]]; then
  echo "INFO: no heartbeat run found; invoking on-demand heartbeat to seed a run id"
  INVOKE_JSON="$(
    run_curl "POST /api/agents/:id/heartbeat/invoke" \
      -sf -X POST \
      -H "${AUTH_HEADER}" \
      -H "Content-Type: application/json" \
      "${BASE_URL}/api/agents/${PAPERCLIP_AGENT_ID}/heartbeat/invoke" \
      -d '{}'
  )"
  RUN_ID="$(printf "%s" "${INVOKE_JSON}" | jq -r '.id // empty')"
fi
if [[ -z "${RUN_ID}" ]]; then
  RUNS_JSON="$(
    run_curl "GET /api/companies/:companyId/heartbeat-runs retry (agentId filter)" \
      -sf -G \
      -H "${AUTH_HEADER}" \
      --data-urlencode "agentId=${PAPERCLIP_AGENT_ID}" \
      --data-urlencode "limit=1" \
      "${BASE_URL}/api/companies/${PAPERCLIP_COMPANY_ID}/heartbeat-runs"
  )"
  RUN_ID="$(printf "%s" "${RUNS_JSON}" | jq -r '.[0].id // empty')"
fi
if [[ -z "${RUN_ID}" ]]; then
  echo "FAIL: could not resolve run id for agent ${PAPERCLIP_AGENT_ID} even after heartbeat invoke" >&2
  exit 1
fi
echo "OK: run id ${RUN_ID}"

ISSUE_ID="${PAPERCLIP_SMOKE_ISSUE_ID:-}"
if [[ -z "${ISSUE_ID}" ]]; then
  ISSUE_ID="$(printf "%s" "${INBOX_JSON}" | jq -r '.[0].id // empty')"
fi

CREATE_EPHEMERAL="${PAPERCLIP_SMOKE_CREATE_EPHEMERAL_ISSUE:-true}"
if [[ -z "${ISSUE_ID}" && "${CREATE_EPHEMERAL}" != "false" ]]; then
  echo "==> 4b/6 Inbox empty; creating ephemeral issue for write checks"
  CREATE_BODY="$(jq -nc \
    --arg aid "${PAPERCLIP_AGENT_ID}" \
    --arg ts "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    '{
      title: ("smoke agent-api ephemeral issue (" + $ts + ")"),
      description: "Auto-generated by scripts/smoke/agent-api.sh",
      status: "todo",
      priority: "low",
      assigneeAgentId: $aid
    }')"
  CREATED_JSON="$(
    run_curl "POST /api/companies/:companyId/issues" \
      -sf -X POST \
      -H "${AUTH_HEADER}" \
      -H "Content-Type: application/json" \
      -H "X-Paperclip-Run-Id: ${RUN_ID}" \
      "${BASE_URL}/api/companies/${PAPERCLIP_COMPANY_ID}/issues" \
      -d "${CREATE_BODY}"
  )"
  CREATED_EPHEMERAL_ISSUE_ID="$(printf "%s" "${CREATED_JSON}" | jq -r '.id // empty')"
  ISSUE_ID="${CREATED_EPHEMERAL_ISSUE_ID}"
  if [[ -z "${ISSUE_ID}" ]]; then
    echo "FAIL: could not create ephemeral issue for write checks" >&2
    exit 1
  fi
  echo "OK: created ephemeral issue ${ISSUE_ID}"
fi

if [[ -z "${ISSUE_ID}" ]]; then
  echo "SKIP: no issue available for write checks (set PAPERCLIP_SMOKE_ISSUE_ID or keep PAPERCLIP_SMOKE_CREATE_EPHEMERAL_ISSUE=true)." >&2
  exit 0
fi

echo "==> 5/6 Write check with X-Paperclip-Run-Id"
BODY_OK='{"comment":"smoke: agent-api write check"}'
run_curl "PATCH /api/issues/:id (with run id)" -sf -X PATCH \
  -H "${AUTH_HEADER}" \
  -H "Content-Type: application/json" \
  -H "X-Paperclip-Run-Id: ${RUN_ID}" \
  "${BASE_URL}/api/issues/${ISSUE_ID}" \
  -d "${BODY_OK}" >/dev/null
echo "OK: write accepted for issue ${ISSUE_ID}"

echo "==> 6/6 Negative check without X-Paperclip-Run-Id (expect 401)"
BODY_NEG='{"comment":"smoke: negative check without run id"}'
if ! STATUS_CODE="$(
  curl "${CURL_OPTS[@]}" -s -o /dev/null -w "%{http_code}" -X PATCH \
    -H "${AUTH_HEADER}" \
    -H "Content-Type: application/json" \
    "${BASE_URL}/api/issues/${ISSUE_ID}" \
    -d "${BODY_NEG}"
)"; then
  echo "FAIL: curl failed (PATCH /api/issues/:id without run id)" >&2
  exit 1
fi

EXPECTED_NEG_CODE="${PAPERCLIP_SMOKE_EXPECT_NO_RUN_ID_STATUS:-}"
if [[ -z "${EXPECTED_NEG_CODE}" ]]; then
  if [[ "${STATUS_CODE}" == "401" ]]; then
    echo "OK: negative check returned 401 (strict run-id enforcement)"
  elif [[ "${STATUS_CODE}" == "200" ]]; then
    echo "WARN: negative check returned 200 (this deployment currently allows PATCH without X-Paperclip-Run-Id)"
  else
    echo "FAIL: expected 401 or 200 without X-Paperclip-Run-Id, got ${STATUS_CODE}" >&2
    exit 1
  fi
elif [[ "${STATUS_CODE}" != "${EXPECTED_NEG_CODE}" ]]; then
  echo "FAIL: expected ${EXPECTED_NEG_CODE} without X-Paperclip-Run-Id, got ${STATUS_CODE}" >&2
  exit 1
else
  echo "OK: negative check returned ${EXPECTED_NEG_CODE}"
fi

echo
echo "PASS: agent API smoke checks completed successfully."
