{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperclip.fullname" . }}-postgres
  labels:
    {{- include "paperclip.postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-user: {{ .Values.postgres.auth.username | quote }}
  postgres-password: {{ .Values.postgres.auth.password | quote }}
  postgres-db: {{ .Values.postgres.auth.database | quote }}
{{- end }}
