{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperclip.fullname" . }}-postgres
  labels:
    {{- include "paperclip.postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "paperclip.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
