apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperclip.fullname" . }}-paperclip-data
  labels:
    {{- include "paperclip.server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.persistence.size }}
  {{- if .Values.server.persistence.storageClass }}
  storageClassName: {{ .Values.server.persistence.storageClass }}
  {{- end }}
