
import {
  Loader2,
  Chrome,
  Bot,
  TrendingUp,
  TrendingDown,
  Activity,
  Zap,
  Brain,
  Target,
  Trophy,
  Users,
  Eye,
  Heart,
  Share,
  Settings,
  LogOut,
  BarChart3,
  LineChart,
  PieChart,
  Coins,
  DollarSign,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  Play,
  Pause,
  RotateCcw,
  Shuffle,
  Star,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Menu,
  X,
  Search,
  Filter,
  Download,
  Upload,
  Copy,
  Check,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Info,
  Bell,
  BellOff,
  Calendar,
  Clock,
  MapPin,
  Globe,
  Link,
  Mail,
  Phone,
  User,
  UserPlus,
  Home,
  Wallet,
  Twitter,
  CheckCircle,
  type LucideIcon,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  spinner: Loader2,
  google: Chrome,
  bot: Bot,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  activity: Activity,
  zap: Zap,
  brain: Brain,
  target: Target,
  trophy: Trophy,
  users: Users,
  eye: Eye,
  heart: Heart,
  share: Share,
  settings: Settings,
  logOut: LogOut,
  barChart: BarChart3,
  lineChart: LineChart,
  pieChart: PieChart,
  coins: Coins,
  dollarSign: DollarSign,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowRight: ArrowRight,
  play: Play,
  pause: Pause,
  refresh: RotateCcw,
  shuffle: Shuffle,
  star: Star,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  menu: Menu,
  x: X,
  search: Search,
  filter: Filter,
  download: Download,
  upload: Upload,
  copy: Copy,
  check: Check,
  alertCircle: AlertCircle,
  checkCircle2: CheckCircle2,
  xCircle: XCircle,
  info: Info,
  bell: Bell,
  bellOff: BellOff,
  calendar: Calendar,
  clock: Clock,
  mapPin: MapPin,
  globe: Globe,
  link: Link,
  mail: Mail,
  phone: Phone,
  user: User,
  userPlus: UserPlus,
  home: Home,
  dashboard: BarChart3,
  wallet: Wallet,
  twitter: Twitter,
  checkCircle: CheckCircle,
};
