import { Router } from "express";
import type { Db } from "@ironworksai/db";
import { knowledgePages, knowledgePageRevisions } from "@ironworksai/db";
import { and, desc, eq } from "drizzle-orm";
import { badRequest, notFound } from "../errors.js";
import { assertCanWrite, assertCompanyAccess, getActorInfo } from "./authz.js";
import { logActivity } from "../services/index.js";

export function announcementRoutes(db: Db) {
  const router = Router();

  // ── GET /companies/:companyId/announcements ─────────────────────────────
  router.get("/companies/:companyId/announcements", async (req, res) => {
    const companyId = req.params.companyId as string;
    assertCompanyAccess(req, companyId);

    const rows = await db
      .select({
        id: knowledgePages.id,
        companyId: knowledgePages.companyId,
        slug: knowledgePages.slug,
        title: knowledgePages.title,
        body: knowledgePages.body,
        visibility: knowledgePages.visibility,
        documentType: knowledgePages.documentType,
        createdByUserId: knowledgePages.createdByUserId,
        createdByAgentId: knowledgePages.createdByAgentId,
        createdAt: knowledgePages.createdAt,
        updatedAt: knowledgePages.updatedAt,
      })
      .from(knowledgePages)
      .where(
        and(
          eq(knowledgePages.companyId, companyId),
          eq(knowledgePages.documentType, "announcement"),
          eq(knowledgePages.visibility, "company_announcement"),
        ),
      )
      .orderBy(desc(knowledgePages.createdAt))
      .limit(50);

    res.json(rows);
  });

  // ── POST /companies/:companyId/announcements ────────────────────────────
  router.post("/companies/:companyId/announcements", async (req, res) => {
    const companyId = req.params.companyId as string;
    await assertCanWrite(req, companyId, db);

    const { title, body } = req.body as Record<string, unknown>;

    if (!title || typeof title !== "string" || title.trim().length === 0) {
      throw badRequest("title is required");
    }
    if (title.trim().length > 200) {
      throw badRequest("title must be 200 characters or less");
    }

    const content = typeof body === "string" ? body : "";
    const slugBase = title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 50);
    const now = new Date();
    const dateSlug = now.toLocaleDateString("en-CA", { timeZone: "America/Chicago" }).replace(/-/g, "");

    // Ensure unique slug
    let slug = `announcement-${slugBase}-${dateSlug}`;
    let suffix = 2;
    while (true) {
      const [existing] = await db
        .select({ id: knowledgePages.id })
        .from(knowledgePages)
        .where(and(eq(knowledgePages.companyId, companyId), eq(knowledgePages.slug, slug)))
        .limit(1);
      if (!existing) break;
      slug = `announcement-${slugBase}-${dateSlug}-${suffix++}`;
    }

    const actor = getActorInfo(req);

    const [page] = await db
      .insert(knowledgePages)
      .values({
        companyId,
        slug,
        title: title.trim(),
        body: content,
        visibility: "company_announcement",
        documentType: "announcement",
        autoGenerated: false,
        createdByUserId: actor.actorType === "user" ? actor.actorId : null,
        createdByAgentId: actor.actorType === "agent" ? actor.actorId : null,
        updatedByUserId: actor.actorType === "user" ? actor.actorId : null,
        updatedByAgentId: actor.actorType === "agent" ? actor.actorId : null,
      })
      .returning();

    await db.insert(knowledgePageRevisions).values({
      pageId: page!.id,
      companyId,
      revisionNumber: 1,
      title: title.trim(),
      body: content,
      changeSummary: "Announcement created",
      editedByUserId: actor.actorType === "user" ? actor.actorId : null,
      editedByAgentId: actor.actorType === "agent" ? actor.actorId : null,
    });

    await logActivity(db, {
      companyId,
      actorType: actor.actorType,
      actorId: actor.actorId,
      agentId: actor.agentId,
      runId: actor.runId,
      action: "announcement.created",
      entityType: "knowledge_page",
      entityId: page!.id,
      details: { title: title.trim() },
    });

    res.status(201).json(page);
  });

  // ── DELETE /companies/:companyId/announcements/:id ──────────────────────
  // Archives the announcement by changing visibility.
  router.delete("/companies/:companyId/announcements/:id", async (req, res) => {
    const companyId = req.params.companyId as string;
    const id = req.params.id as string;
    await assertCanWrite(req, companyId, db);

    const [existing] = await db
      .select({ id: knowledgePages.id })
      .from(knowledgePages)
      .where(
        and(
          eq(knowledgePages.id, id),
          eq(knowledgePages.companyId, companyId),
          eq(knowledgePages.documentType, "announcement"),
        ),
      )
      .limit(1);

    if (!existing) {
      throw notFound("Announcement not found");
    }

    await db
      .update(knowledgePages)
      .set({
        visibility: "archived",
        updatedAt: new Date(),
        updatedByUserId: "system",
      })
      .where(eq(knowledgePages.id, id));

    const actor = getActorInfo(req);
    await logActivity(db, {
      companyId,
      actorType: actor.actorType,
      actorId: actor.actorId,
      agentId: actor.agentId,
      runId: actor.runId,
      action: "announcement.archived",
      entityType: "knowledge_page",
      entityId: id,
    });

    res.json({ ok: true });
  });

  return router;
}
