import { Router } from "express";
import type { Db } from "@ironworksai/db";
import { and, desc, eq, inArray, isNotNull } from "drizzle-orm";
import { knowledgePages, agents } from "@ironworksai/db";
import { DELIVERABLE_DOCUMENT_TYPES, DELIVERABLE_STATUSES } from "@ironworksai/shared";
import { assertCompanyAccess, assertCanWrite, getActorInfo } from "./authz.js";
import { logActivity } from "../services/activity-log.js";

const DELIVERABLE_TYPES = [...DELIVERABLE_DOCUMENT_TYPES];

export function deliverableRoutes(db: Db) {
  const router = Router();

  // List deliverables for a company
  router.get("/companies/:companyId/deliverables", async (req, res) => {
    const companyId = req.params.companyId as string;
    assertCompanyAccess(req, companyId);

    const status = typeof req.query.status === "string" ? req.query.status : undefined;

    const conditions = [
      eq(knowledgePages.companyId, companyId),
      inArray(knowledgePages.documentType, DELIVERABLE_TYPES),
      isNotNull(knowledgePages.deliverableStatus),
    ];

    if (status && DELIVERABLE_STATUSES.includes(status as typeof DELIVERABLE_STATUSES[number])) {
      conditions.push(eq(knowledgePages.deliverableStatus, status));
    }

    const rows = await db
      .select({
        id: knowledgePages.id,
        companyId: knowledgePages.companyId,
        slug: knowledgePages.slug,
        title: knowledgePages.title,
        documentType: knowledgePages.documentType,
        deliverableStatus: knowledgePages.deliverableStatus,
        agentId: knowledgePages.agentId,
        createdByAgentId: knowledgePages.createdByAgentId,
        autoGenerated: knowledgePages.autoGenerated,
        createdAt: knowledgePages.createdAt,
        updatedAt: knowledgePages.updatedAt,
        agentName: agents.name,
        agentRole: agents.role,
      })
      .from(knowledgePages)
      .leftJoin(agents, eq(knowledgePages.createdByAgentId, agents.id))
      .where(and(...conditions))
      .orderBy(desc(knowledgePages.updatedAt));

    res.json(rows);
  });

  // Update deliverable status (approve, request revision, mark delivered)
  router.patch("/companies/:companyId/deliverables/:id", async (req, res) => {
    const companyId = req.params.companyId as string;
    assertCompanyAccess(req, companyId);
    await assertCanWrite(req, companyId, db);

    const id = req.params.id as string;
    const { deliverableStatus } = req.body as { deliverableStatus?: string };

    if (!deliverableStatus || !DELIVERABLE_STATUSES.includes(deliverableStatus as typeof DELIVERABLE_STATUSES[number])) {
      res.status(400).json({ error: `deliverableStatus must be one of: ${DELIVERABLE_STATUSES.join(", ")}` });
      return;
    }

    const [existing] = await db
      .select({
        id: knowledgePages.id,
        companyId: knowledgePages.companyId,
        deliverableStatus: knowledgePages.deliverableStatus,
        documentType: knowledgePages.documentType,
        title: knowledgePages.title,
      })
      .from(knowledgePages)
      .where(and(eq(knowledgePages.id, id), eq(knowledgePages.companyId, companyId)))
      .limit(1);

    if (!existing) {
      res.status(404).json({ error: "Deliverable not found" });
      return;
    }

    if (!existing.documentType || !(DELIVERABLE_DOCUMENT_TYPES as readonly string[]).includes(existing.documentType)) {
      res.status(400).json({ error: "Page is not a deliverable type" });
      return;
    }

    const [updated] = await db
      .update(knowledgePages)
      .set({ deliverableStatus, updatedAt: new Date() })
      .where(eq(knowledgePages.id, id))
      .returning();

    const actor = getActorInfo(req);
    await logActivity(db, {
      companyId,
      actorType: actor.actorType,
      actorId: actor.actorId,
      action: "deliverable.status_updated",
      entityType: "knowledge_page",
      entityId: id,
      details: { title: existing.title, previousStatus: existing.deliverableStatus, newStatus: deliverableStatus },
    });

    res.json(updated);
  });

  return router;
}
