import { MarkdownBody } from "../components/MarkdownBody";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Shield } from "lucide-react";

const PRIVACY_POLICY = `
# Privacy Policy

**Version:** v0.1 — pending legal review
**Effective Date:** April 1, 2026
**Last Updated:** April 1, 2026

IronWorks ("we," "us," "our") is operated by Steel Motion LLC. This Privacy Policy describes how we collect, use, store, and protect your information when you use the IronWorks platform.

## 1. Data Processing Roles

### 1.1 Steel Motion as Data Processor
Steel Motion LLC operates as a **data processor** under applicable data protection law. We process personal data on behalf of and under the instructions of our clients.

### 1.2 Client as Data Controller
Our clients ("you," "your") are the **data controllers**. You determine the purposes and means of processing personal data through the IronWorks platform. You are responsible for ensuring you have a lawful basis for processing.

### 1.3 Data Processing Agreement
For detailed information about our processing obligations and your rights as a controller, please refer to our [Data Processing Agreement](/dpa).

## 2. Information We Collect

### 2.1 Account Information
- Email address and name (when using authenticated mode)
- Authentication tokens and session data
- IP address at login

### 2.2 Company & Agent Data
- Company name, description, and configuration
- AI agent profiles, instructions, and configurations
- Projects, issues, goals, and associated metadata
- Comments, approvals, and collaboration data
- Playbook definitions and execution history

### 2.3 Execution Data
- Agent heartbeat run logs and events
- Token usage and cost tracking data
- Activity audit logs
- Library files and documents created by agents

### 2.4 Technical Data
- Browser type and version (via user-agent)
- Session cookies (strictly necessary for authentication)
- Optional analytics data (only with your consent)

## 3. What We Do NOT Collect

### 3.1 LLM API Keys
Your third-party LLM API keys are **encrypted at rest using AES-256** and are never accessed, read, or logged by Steel Motion personnel. Keys are used exclusively to execute API calls on your behalf as directed by your agent configurations.

### 3.2 Agent Output Content
Steel Motion does **not** read, review, moderate, or access the content generated by your AI agents. We are a platform provider — your agent output belongs to you and is not monitored by us.

### 3.3 No Data Selling or Model Training
We do **not**:
- Sell your personal data to third parties
- Use your data for advertising
- Train AI models on your company data
- Share your data with other customers

## 4. How We Use Your Information

We use your information solely to:

- **Operate the platform** — authenticate you, run your AI agents, track costs, and deliver features
- **Maintain security** — detect unauthorized access, prevent abuse, and protect your data
- **Improve the product** — analyze usage patterns (with consent) to improve features and performance
- **Process billing** — manage subscriptions and process payments through Stripe
- **Comply with legal obligations** — respond to lawful requests and enforce our terms

## 5. Data Storage & Security

### 5.1 Where Data is Stored
- All data is stored on infrastructure you control (self-hosted) or on our managed VPS infrastructure
- For self-hosted deployments, data never leaves your server
- For managed deployments, data is stored on encrypted VPS instances

### 5.2 Security Measures
- All data at rest is stored in PostgreSQL with filesystem-level encryption
- API keys and secrets are encrypted with AES-256 using a master key
- Authentication uses secure session tokens with expiration
- Agent API keys use SHA-256 hashed storage
- SVG uploads are sanitized to prevent XSS
- Path traversal protection on all file access endpoints

### 5.3 Data Isolation
- Each company's data is isolated by company ID
- Agents can only access data within their own company
- Library file access is governed by org-chart-based ACLs

## 6. Data Retention

We retain data for the following periods:

| Data Type | Retention Period | Purpose |
|---|---|---|
| Active account data | Duration of account | Service operation |
| Agent execution logs | 90 days | Debugging and audit |
| Activity logs | 365 days | Compliance and audit trail |
| Cost/billing events | 365 days | Financial records |
| Expired auth sessions | 30 days after expiry | Security cleanup |
| Plugin logs | 7 days | Debugging |

### 6.1 After Account Termination
- Active account data is deleted within **30 days** of termination
- Backup copies are deleted within **90 days** of termination
- Data is automatically cleaned up daily after retention periods expire

## 7. Data Export

You can export your company data at any time through the IronWorks platform:

- Navigate to **Company Settings > Export** to download a complete export of all your company data in machine-readable JSON format
- Export includes agents, projects, issues, goals, activity logs, and associated metadata
- You may also request a full data export by contacting privacy@steelmotionllc.ai

## 8. Sub-processors

Steel Motion uses the following sub-processors to provide the Service:

| Sub-processor | Purpose | Location |
|---|---|---|
| Contabo GmbH | Infrastructure hosting (VPS) | Germany / United States |
| Stripe, Inc. | Payment processing and billing | United States |

We will notify you at least 30 days in advance before engaging any new sub-processors. For details on sub-processor management, see our [Data Processing Agreement](/dpa).

## 9. Cookies

### 9.1 Strictly Necessary Cookies
- **Session cookie** — required for authentication. Cannot be disabled.

### 9.2 Optional Cookies (Consent Required)
- **Analytics** — help us understand usage patterns. Disabled by default.
- **Preferences** — remember your display settings. Disabled by default.

You can manage your cookie preferences at any time by clicking "Cookie Settings" in the page footer.

## 10. Your Rights

### 10.1 GDPR Rights (EEA Residents)

**Right to Access (Article 15):** You can view a summary of all data we store about your company in **Settings > Privacy & Data**.

**Right to Data Portability (Article 20):** You can download a complete export of all your data in machine-readable JSON format from **Settings > Privacy & Data > Export Your Data**.

**Right to Erasure (Article 17):** You can request permanent deletion of all your data from **Settings > Privacy & Data > Request Data Erasure**. Erasure is scheduled with a 30-day grace period, after which all data is permanently and irreversibly removed.

**Right to Rectification (Article 16):** You can update your company information, agent configurations, and other data directly through the IronWorks interface.

**Right to Object (Article 21):** You can disable optional cookies and analytics tracking at any time through the Cookie Settings accessible from any page footer.

**Right to Restrict Processing:** You may request that we restrict the processing of your personal data under certain circumstances by contacting us.

### 10.2 CCPA Rights (California Residents)
- **Right to Know:** You can request a summary of personal information collected (Settings > Privacy & Data)
- **Right to Delete:** You can request deletion of your data (Settings > Privacy & Data > Request Data Erasure)
- **Right to Opt-Out of Sale:** We do not sell personal information. No opt-out is necessary.
- **Non-Discrimination:** We will not discriminate against you for exercising your privacy rights.

## 11. Third-Party Services

### 11.1 AI Model Providers
When you configure AI agents, your prompts and agent instructions are sent to your chosen AI provider (Anthropic, OpenAI, Google, etc.). Each provider has their own privacy policy governing how they handle this data. IronWorks does not control how AI providers process your data.

### 11.2 No Other Third Parties
We do not use third-party analytics, advertising, or tracking services unless you explicitly enable them.

## 12. Children's Privacy

IronWorks is not intended for use by individuals under 16 years of age. We do not knowingly collect personal information from children.

## 13. Changes to This Policy

We may update this Privacy Policy from time to time. We will notify you of material changes by updating the "Last Updated" date and, for significant changes, by displaying a notice in the application.

## 14. Contact Us

For privacy-related questions, data requests, or concerns:

- **Email:** privacy@steelmotionllc.ai
- **Company:** Steel Motion LLC
- **Website:** ironworksapp.ai
- **Response Time:** We respond to all privacy requests within 30 days as required by GDPR and CCPA.

---

*This Privacy Policy applies to the IronWorks platform operated by Steel Motion LLC.*
`;

export function PrivacyPolicy() {
  return (
    <div className="min-h-[100dvh] bg-background">
      <ScrollArea className="h-[100dvh]">
        <div className="max-w-2xl mx-auto px-6 py-12">
          <div className="flex items-center gap-2 mb-6">
            <Shield className="h-5 w-5 text-muted-foreground" />
            <span className="text-sm text-muted-foreground">IronWorks by Steel Motion LLC</span>
          </div>
          <MarkdownBody>{PRIVACY_POLICY}</MarkdownBody>
          <div className="mt-12 pt-6 border-t border-border text-xs text-muted-foreground">
            <p>Steel Motion LLC. All rights reserved.</p>
          </div>
        </div>
      </ScrollArea>
    </div>
  );
}
