import type { CreateConfigValues } from "@paperclipai/adapter-utils";

export const defaultCreateValues: CreateConfigValues = {
  adapterType: "claude_local",
  cwd: "",
  instructionsFilePath: "",
  promptTemplate: "",
  model: "",
  thinkingEffort: "",
  chrome: false,
  dangerouslySkipPermissions: true,
  search: false,
  dangerouslyBypassSandbox: false,
  command: "",
  args: "",
  extraArgs: "",
  envVars: "",
  envBindings: {},
  url: "",
  openClawGatewayToken: "",
  openClawPaperclipApiUrl: "",
  openClawRole: "operator",
  openClawScopes: "operator.admin",
  openClawWaitTimeoutMs: "120000",
  openClawSessionKeyStrategy: "issue",
  openClawSessionKey: "paperclip",
  bootstrapPrompt: "",
  payloadTemplateJson: "",
  workspaceStrategyType: "project_primary",
  workspaceBaseRef: "",
  workspaceBranchTemplate: "",
  worktreeParentDir: "",
  runtimeServicesJson: "",
  maxTurnsPerRun: 300,
  heartbeatEnabled: false,
  intervalSec: 300,
};
