export const API_PREFIX = "/api";

export const API = {
  health: `${API_PREFIX}/health`,
  companies: `${API_PREFIX}/companies`,
  agents: `${API_PREFIX}/agents`,
  projects: `${API_PREFIX}/projects`,
  issues: `${API_PREFIX}/issues`,
  goals: `${API_PREFIX}/goals`,
  approvals: `${API_PREFIX}/approvals`,
  secrets: `${API_PREFIX}/secrets`,
  costs: `${API_PREFIX}/costs`,
  activity: `${API_PREFIX}/activity`,
  dashboard: `${API_PREFIX}/dashboard`,
  sidebarBadges: `${API_PREFIX}/sidebar-badges`,
  invites: `${API_PREFIX}/invites`,
  joinRequests: `${API_PREFIX}/join-requests`,
  members: `${API_PREFIX}/members`,
  admin: `${API_PREFIX}/admin`,
  chat: {
    conversations: `${API_PREFIX}/companies/:companyId/chat/conversations`,
    channels: `${API_PREFIX}/companies/:companyId/chat/channels`,
    dms: `${API_PREFIX}/companies/:companyId/chat/dms`,
    conversation: `${API_PREFIX}/chat/conversations/:conversationId`,
    conversationMessages: `${API_PREFIX}/chat/conversations/:conversationId/messages`,
    message: `${API_PREFIX}/chat/messages/:messageId`,
    messageReactions: `${API_PREFIX}/chat/messages/:messageId/reactions`,
    messageReaction: `${API_PREFIX}/chat/messages/:messageId/reactions/:emoji`,
    conversationRead: `${API_PREFIX}/chat/conversations/:conversationId/read`,
    search: `${API_PREFIX}/companies/:companyId/chat/search`,
  },
} as const;
