import {
  boolean,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { agents } from "./agents.js";
import { companies } from "./companies.js";
import { projects } from "./projects.js";

export const knowledgePages = pgTable(
  "knowledge_pages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
    /** URL-safe slug, unique per company. */
    slug: text("slug").notNull(),
    title: text("title").notNull(),
    /** Markdown body, max 100KB enforced at app layer. */
    body: text("body").notNull().default(""),
    /** company = visible to all, project = scoped to a project, private = only creator. */
    visibility: text("visibility").notNull().default("company"),
    /** Optional project scope when visibility = project. */
    projectId: uuid("project_id").references(() => projects.id, { onDelete: "set null" }),
    /** Current revision number (incremented on each edit). */
    revisionNumber: integer("revision_number").notNull().default(1),
    /** Is this a system-seeded page? */
    isSeeded: text("is_seeded"),
    createdByAgentId: uuid("created_by_agent_id").references(() => agents.id, { onDelete: "set null" }),
    createdByUserId: text("created_by_user_id"),
    updatedByAgentId: uuid("updated_by_agent_id").references(() => agents.id, { onDelete: "set null" }),
    updatedByUserId: text("updated_by_user_id"),
    /** Optional agent scope - which agent's workspace this page belongs to. */
    agentId: uuid("agent_id").references(() => agents.id, { onDelete: "set null" }),
    /** Document classification: report, decision, review, personnel, note, folder, etc. */
    documentType: text("document_type"),
    /** System-created vs manually created. */
    autoGenerated: boolean("auto_generated").notNull().default(false),
    /** Department scope for department-level knowledge. */
    department: text("department"),
    /**
     * Workflow status for auto-generated deliverables.
     * Values: draft | review | approved | delivered
     * Set automatically when document_type is a deliverable type and auto_generated = true.
     */
    deliverableStatus: text("deliverable_status"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companySlugUq: uniqueIndex("knowledge_pages_company_slug_uq").on(table.companyId, table.slug),
    companyUpdatedIdx: index("knowledge_pages_company_updated_idx").on(table.companyId, table.updatedAt),
    companyVisibilityIdx: index("knowledge_pages_company_visibility_idx").on(table.companyId, table.visibility),
    agentIdx: index("knowledge_pages_agent_id_idx").on(table.agentId),
    companyDocTypeIdx: index("knowledge_pages_company_document_type_idx").on(table.companyId, table.documentType),
    companyDeliverableIdx: index("knowledge_pages_company_deliverable_idx").on(table.companyId, table.deliverableStatus),
  }),
);

export const knowledgePageRevisions = pgTable(
  "knowledge_page_revisions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    pageId: uuid("page_id").notNull().references(() => knowledgePages.id, { onDelete: "cascade" }),
    companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
    revisionNumber: integer("revision_number").notNull(),
    title: text("title").notNull(),
    body: text("body").notNull(),
    changeSummary: text("change_summary"),
    editedByAgentId: uuid("edited_by_agent_id").references(() => agents.id, { onDelete: "set null" }),
    editedByUserId: text("edited_by_user_id"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    pageRevisionIdx: index("knowledge_page_revisions_page_idx").on(table.pageId, table.revisionNumber),
  }),
);
