import { and, eq } from "drizzle-orm";
import type { Db } from "@ironworksai/db";
import { agents } from "@ironworksai/db";
import { createAgentDocument } from "./agent-workspace.js";
import { logger } from "../middleware/logger.js";

type EmploymentEventType = "hired" | "department_change" | "performance_review" | "promotion" | "terminated";

// ── HR Personnel File Management ────────────────────────────────────────────
//
// Creates auto-generated knowledge pages for personnel records.
// If a VP of HR agent exists in the company, documents are scoped to that
// agent's workspace. Otherwise they are created with agent_id = null.

function slugifyName(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    || "agent";
}

function formatDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}

/**
 * Find the VP of HR agent for a company, if one exists.
 */
async function findHrAgent(db: Db, companyId: string): Promise<string | null> {
  const [hr] = await db
    .select({ id: agents.id })
    .from(agents)
    .where(
      and(
        eq(agents.companyId, companyId),
        eq(agents.role, "vp_hr"),
      ),
    )
    .limit(1);

  if (hr) return hr.id;

  // Also check for common role name variations
  const rows = await db
    .select({ id: agents.id, role: agents.role })
    .from(agents)
    .where(eq(agents.companyId, companyId));

  for (const row of rows) {
    const r = row.role.toLowerCase();
    if (
      (r.includes("hr") && (r.includes("vp") || r.includes("vice") || r.includes("head"))) ||
      r === "hr_director"
    ) {
      return row.id;
    }
  }

  return null;
}

/**
 * Create a hiring record when a new agent is hired.
 */
export async function createHiringRecord(
  db: Db,
  opts: {
    companyId: string;
    hrAgentId: string | null;
    hiredAgentId: string;
    hiredAgentName: string;
    hiredAgentRole: string;
    employmentType: string;
    hiredByUserId: string | null;
    hiredByAgentId: string | null;
  },
): Promise<void> {
  const {
    companyId,
    hiredAgentId,
    hiredAgentName,
    hiredAgentRole,
    employmentType,
    hiredByUserId,
    hiredByAgentId,
  } = opts;

  // Resolve HR agent if not provided
  const hrAgentId = opts.hrAgentId ?? await findHrAgent(db, companyId);

  const nameSlug = slugifyName(hiredAgentName);
  const date = formatDate(new Date());
  const slug = `hr-personnel-${nameSlug}-hiring-${date}`;

  const hiredBy = hiredByUserId
    ? `Board User (${hiredByUserId})`
    : hiredByAgentId
      ? `Agent (${hiredByAgentId})`
      : "System";

  const content = [
    `# Hiring Record - ${hiredAgentName}`,
    "",
    "## Agent Information",
    `- **Name:** ${hiredAgentName}`,
    `- **Role:** ${hiredAgentRole}`,
    `- **Employment Type:** ${employmentType}`,
    `- **Hired Date:** ${date}`,
    `- **Hired By:** ${hiredBy}`,
    "",
    "## Status",
    "- **Current Status:** idle (newly hired)",
    "",
    "## Notes",
    "",
    "[VP of HR adds onboarding notes here]",
  ].join("\n");

  await createAgentDocument(db, {
    agentId: hrAgentId ?? hiredAgentId,
    companyId,
    title: `Hiring Record - ${hiredAgentName}`,
    content,
    documentType: "personnel",
    slug,
    department: "hr",
    visibility: hrAgentId ? "private" : "company",
    autoGenerated: true,
    createdByUserId: "system",
  });

  logger.info(
    { companyId, hiredAgentId, hiredAgentName, hrAgentId },
    "hiring record created",
  );
}

/**
 * Create a termination record when an agent is terminated.
 */
export async function createTerminationRecord(
  db: Db,
  opts: {
    companyId: string;
    hrAgentId: string | null;
    terminatedAgentId: string;
    terminatedAgentName: string;
    reason: string;
  },
): Promise<void> {
  const {
    companyId,
    terminatedAgentId,
    terminatedAgentName,
    reason,
  } = opts;

  const hrAgentId = opts.hrAgentId ?? await findHrAgent(db, companyId);

  const nameSlug = slugifyName(terminatedAgentName);
  const date = formatDate(new Date());
  const slug = `hr-personnel-${nameSlug}-termination-${date}`;

  const content = [
    `# Termination Record - ${terminatedAgentName}`,
    "",
    "## Agent Information",
    `- **Name:** ${terminatedAgentName}`,
    `- **Terminated Date:** ${date}`,
    `- **Termination Reason:** ${reason}`,
    "",
    "## Offboarding Checklist",
    "- [ ] Workspace archived",
    "- [ ] Active issues reassigned",
    "- [ ] Memory entries archived",
    "- [ ] Personnel file closed",
    "",
    "## Notes",
    "",
    "[VP of HR adds final notes here]",
  ].join("\n");

  await createAgentDocument(db, {
    agentId: hrAgentId ?? terminatedAgentId,
    companyId,
    title: `Termination Record - ${terminatedAgentName}`,
    content,
    documentType: "personnel",
    slug,
    department: "hr",
    visibility: hrAgentId ? "private" : "company",
    autoGenerated: true,
    createdByUserId: "system",
  });

  logger.info(
    { companyId, terminatedAgentId, terminatedAgentName, hrAgentId },
    "termination record created",
  );
}

/**
 * Create a performance review document for an agent.
 */
export async function createPerformanceReview(
  db: Db,
  opts: {
    companyId: string;
    hrAgentId: string | null;
    reviewedAgentId: string;
    reviewedAgentName: string;
    performanceScore: number;
    summary: string;
  },
): Promise<void> {
  const {
    companyId,
    reviewedAgentId,
    reviewedAgentName,
    performanceScore,
    summary,
  } = opts;

  const hrAgentId = opts.hrAgentId ?? await findHrAgent(db, companyId);

  const nameSlug = slugifyName(reviewedAgentName);
  const date = formatDate(new Date());
  const slug = `hr-personnel-${nameSlug}-review-${date}`;

  // Derive letter grade from score
  let grade = "F";
  if (performanceScore >= 90) grade = "A";
  else if (performanceScore >= 80) grade = "B";
  else if (performanceScore >= 70) grade = "C";
  else if (performanceScore >= 60) grade = "D";

  const content = [
    `# Performance Review - ${reviewedAgentName} - ${date}`,
    "",
    "## Metrics",
    `- **Performance Score:** ${performanceScore} (${grade} rating)`,
    "",
    "## Summary",
    summary,
    "",
    "## Strengths",
    "",
    "[To be filled by VP of HR]",
    "",
    "## Areas for Improvement",
    "",
    "[To be filled by VP of HR]",
    "",
    "## Recommendation",
    "",
    "[continue / promote / PIP / terminate]",
  ].join("\n");

  await createAgentDocument(db, {
    agentId: hrAgentId ?? reviewedAgentId,
    companyId,
    title: `Performance Review - ${reviewedAgentName} - ${date}`,
    content,
    documentType: "review",
    slug,
    department: "hr",
    visibility: hrAgentId ? "private" : "company",
    autoGenerated: true,
    createdByUserId: "system",
  });

  logger.info(
    { companyId, reviewedAgentId, reviewedAgentName, performanceScore, hrAgentId },
    "performance review created",
  );
}

/**
 * Create an employment history entry for tracking significant agent lifecycle events.
 *
 * Creates a knowledge page in the HR personnel folder with document_type
 * "employment_history". These entries build a chronological record of
 * each agent's career events.
 */
export async function createEmploymentHistoryEntry(
  db: Db,
  opts: {
    companyId: string;
    agentId: string;
    agentName: string;
    eventType: EmploymentEventType;
    details: string;
  },
): Promise<void> {
  const { companyId, agentId, agentName, eventType, details } = opts;

  const hrAgentId = await findHrAgent(db, companyId);
  const nameSlug = slugifyName(agentName);
  const date = formatDate(new Date());
  const slug = `hr-employment-history-${nameSlug}-${eventType}-${date}`;

  const eventLabel: Record<EmploymentEventType, string> = {
    hired: "Hiring",
    department_change: "Department Change",
    performance_review: "Performance Review",
    promotion: "Promotion",
    terminated: "Termination",
  };

  const content = [
    `# Employment History - ${agentName} - ${eventLabel[eventType]}`,
    "",
    "## Event Details",
    `- **Agent:** ${agentName}`,
    `- **Event Type:** ${eventLabel[eventType]}`,
    `- **Date:** ${date}`,
    "",
    "## Details",
    details,
    "",
    "## Notes",
    "",
    "[VP of HR adds notes here]",
  ].join("\n");

  await createAgentDocument(db, {
    agentId: hrAgentId ?? agentId,
    companyId,
    title: `Employment History - ${agentName} - ${eventLabel[eventType]} - ${date}`,
    content,
    documentType: "employment_history",
    slug,
    department: "hr",
    visibility: hrAgentId ? "private" : "company",
    autoGenerated: true,
    createdByUserId: "system",
  });

  logger.info(
    { companyId, agentId, agentName, eventType, hrAgentId },
    "employment history entry created",
  );
}
